name: 'Testy'
description: 'Display test results in a GitHub Actions workflow'
author: 'Edward Thomson'
inputs:
  paths:
    description: Path(s) to test output file(s) to analyze
    required: true
  output:
    description: File to write with rendered output
    required: true
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: check-square
  color: blue
